version: "3.9"

services:
  api:
    image: amitkumaramit/eclaim_api:1.0
    container_name: eclaim_api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Redis=redis:6379,abortConnect=false,connectTimeout=15000
      # - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EClaimAppDb;User Id=SA;Password=Amit@123;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      redis:
        condition: service_healthy
      # sqlserver:
      #   condition: service_started
    networks:
      - eclaimnet

  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: sqlserver
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=Amit@123
  #   volumes:
  #     - sql_data:/var/opt/mssql
  #   healthcheck:
  #     test: ["CMD-SHELL", "sqlcmd -S sqlserver -U SA -P Amit@123 -Q 'SELECT 1'"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - eclaimnet

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - eclaimnet

networks:
  eclaimnet:
    driver: bridge

volumes:
  redis_data:
  # sql_data:
