services:
  api:
    build: 
      context: .
      dockerfile: EClaim.API/Dockerfile
    container_name: eclaim_api_repo
    ports:
      - "5000:80"
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Redis=redis:6379,abortConnect=false,connectTimeout=15000
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - eclaimnet

  redis:
    image: redis:7
    container_name: redis_repo
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - eclaimnet

networks:
  eclaimnet:

volumes:
  redis_data:
